### ISSUE TITLE
about eval_split function

### ISSUE THREAD

**Issue by BladeSun** [cheng6076/SNLI-attention#11]
in line 153
`local max,indice = prediction:max(2)   -- indice is a 2d tensor here, we need to flatten it...
 if indice[1][1] == label[1] then correct_count = correct_count + 1 end`
It seems only check the first result of a batch. why not check them all?

**Comment by cheng6076** [comment]
You might use the following if you are not changing the dataset:

    protos.classifier:evaluate()
    local prediction = protos.classifier:forward({rnn_h_enc, rnn_h_dec})
    local max,indice = prediction:max(2)   
    for j=1, opt.batch_size do
      if indice[j][1] == label[j] then
        correct_count = correct_count + 1
      else
   end
