### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Achilles-96** [cheng6076/SNLI-attention#15]
Thank you very much for updating :D . But, one last problem. Can you tell me how much memory is needed for this. I have 4GB GTX 960M but it throws out of memory error.

**Comment by cheng6076** [comment]
Hi Achilles, it takes 8-9 GB

**Comment by Achilles-96** [comment]
Now, I am using a 12GB GPU and it still runs out of memory. This is what I am doing.
I place snli train, test and dev data in data dir after cloning with appropriate names.
After that, I point `input_w2v` variable to `glove.840B.300d.txt`. 
I run it as `th main.lua`.

Please tell me if I am doing something wrong. Word embedding file is 5.3GB.

**Comment by cheng6076** [comment]
Same as what I did. Can you try to use smaller mini batch?

**Comment by Achilles-96** [comment]
@cheng6076 , Batch size of 25 works fine. Thanks. Cheers.
