### ISSUE TITLE
Mac os couldn't run

### ISSUE THREAD

**Issue by iamsile** [cheng6076/SNLI-attention#3]
Hi, When I use it on mac os. It couldn't work.

Processing text into tensors...	
/Users/xxxxx/torch/install/bin/luajit: ./util/BatchLoaderC.lua:81: attempt to index local 'f' (a nil value)
stack traceback:
	./util/BatchLoaderC.lua:81: in function 'text_to_tensor'
	./util/BatchLoaderC.lua:15: in function 'create'
	LSTMN.lua:62: in main chunk
	[C]: in function 'dofile'
	...owei/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x010580e2d0

**Comment by SreeHarshaRamesh** [comment]
@iamsile I think this is because there was no data in the data folder. 

> this folder should include:
> train.txt
> dev.text
> test.txt
> word2vec.txt
> *******************
> SNLI format:
> label(0, 1, 2) \t sentence1 \t sentence2 \n
> 
> word2vec format:
> word 300d_vector \n

Almost created an issue for this myself, when I saw that the data folder was empty.

@cheng6076 Would it be possible to update the repository with some sample data? Thanks, H

**Comment by iamsile** [comment]
OK, thank you! @SreeHarshaRamesh Let me have a try
