### ISSUE TITLE
enc_lookup

### ISSUE THREAD

**Issue by BladeSun** [cheng6076/SNLI-attention#5]
/opt/torch/install/bin/luajit: LSTMN.lua:301: attempt to index global 'enc_lookup' (a nil value)
stack traceback:
        LSTMN.lua:301: in main chunk
        [C]: in function 'dofile'
        /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064d0

**Comment by cheng6076** [comment]
It should be ok now.

**Comment by BladeSun** [comment]
Thanks very much @cheng6076
