### ISSUE TITLE
AddScalar

### ISSUE THREAD

**Issue by BladeSun** [cheng6076/SNLI-attention#6]
/opt/torch/install/bin/luajit: ./model/encoder_lstmn_w2v.lua:38: attempt to call field 'AddScalar' (a nil value)
stack traceback:
        ./model/encoder_lstmn_w2v.lua:38: in function 'lstmn'
        LSTMN.lua:70: in main chunk
        [C]: in function 'dofile'
        /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064d0

Does 'AddScalar' do the same as 'ReplicateAdd' in the previous version?

**Comment by cheng6076** [comment]
fixed now.
